### ISSUE TITLE
没有注册、无法登录

### ISSUE THREAD

**Issue by dq1717** [yuzg667/covGo#1]
1. 没有用户注册的入口，“后台管理”进入就是登录，但是数据库init.sql没有初始化任何账号，怎么操作？多谢
2. 我在数据库里手工添加了user、group、permission相关的表数据，但是登录时提示"请输入一个正确的 用户名 和密码. 注意他们都是区分大小写的. "，是数据库的密码存储是加密的吗？
3. 是要登录成功后，才能有看到创建项目和创建任务的入口吗？
备注：我用的代码手工安装，goc等其他依赖都是可用的

**Comment by yuzg667** [comment]
进入docker容器, 切换到目录/home/workspace/covGo/
执行命令行，可创建一个超级用户。
`python3 manage.py createsuperuser`
